# Generated by Django 3.2.11 on 2022-01-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanessa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='nivel',
            field=models.CharField(choices=[('C', 'Corporal'), ('P', 'Pé e Mão'), ('D', 'Depilação')], default='C', max_length=1),
        ),
    ]
