# Generated by Django 3.2.11 on 2022-01-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanessa_app', '0004_auto_20220120_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nivel',
            field=models.CharField(choices=[('Corporal', 'Corporal'), ('Pé e Mão', 'Pé e Mão'), ('Depilação', 'Depilação')], default='C', max_length=30),
        ),
    ]
