# Generated by Django 4.0.1 on 2022-01-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanessa_app', '0007_alter_atendimento_id_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(default='', max_length=13),
        ),
    ]
